version: 'RockLib.Configuration.ObjectFactory.{build}.0.0-ci'
image: Visual Studio 2017
configuration: Release
only_commits:
 files:
   - RockLib.Configuration.ObjectFactory/
   - RockLib.Configuration.ObjectFactory.UnitTests/
   - RockLib.Configuration.ObjectFactory.sln
   - RockLib.Configuration.ObjectFactory.appveyor.yml
before_build:
   - ps: |
      $sln_path = "RockLib.Configuration.ObjectFactory.sln"
      $csproj_path = "RockLib.Configuration.ObjectFactory\RockLib.Configuration.ObjectFactory.csproj"
      
      $commit_message = "$Env:appveyor_repo_commit_message`n`n$Env:appveyor_repo_commit_message_extended".Replace("\n", "`n").TrimEnd()
      
      $csproj = [xml](Get-Content $csproj_path)
      
      $package_version_node = $csproj.SelectSingleNode("/Project/PropertyGroup/PackageVersion")

      $package_id = $csproj.SelectSingleNode("/Project/PropertyGroup/PackageId").InnerText
      $package_version = $package_version_node.InnerText
      $csproj_build_version = "$package_id.$package_version"
      
      If ($Env:appveyor_repo_tag -eq "true" -AND $Env:appveyor_repo_tag_name -eq $csproj_build_version) {
         Update-AppVeyorBuild -Version $csproj_build_version
      } else {
         $package_version_node.InnerText = "$Env:appveyor_build_number.0.0-ci"
      }
      
      $package_release_notes_node = $csproj.SelectSingleNode("/Project/PropertyGroup/PackageReleaseNotes")
      $package_release_notes_node.InnerText = $commit_message
      
      $csproj.Save((Get-Item $csproj_path))
      
      nuget restore $sln_path
build:
  project: RockLib.Configuration.ObjectFactory.sln
  verbosity: minimal
artifacts:
- path: '**\RockLib.Configuration.ObjectFactory.*.nupkg'
deploy:
- provider: GitHub
  tag: $(appveyor_repo_tag_name)
  release: $(appveyor_repo_commit_message)
  description: $(appveyor_repo_commit_message_extended)
  auth_token:
    secure: yjDw1QLeuxM3Wvq9ZEJIB8JaEK/L2e7MhwrKicm3/SBh0FwbAEb3Fpg82h0fFALU
  on:
    appveyor_repo_tag: true
    appveyor_repo_tag_name: $(appveyor_build_version)
- provider: NuGet
  api_key:
    secure: n0btQo8iZJZTJ3S5vLWokuOxzv4dtYBi3cx6EbW41jTF5OfcshJs+dTMAGCTquLY
  on:
    appveyor_repo_tag: true
    appveyor_repo_tag_name: $(appveyor_build_version)
notifications:
- provider: Email
  to:
  - brianfriesen@quickenloans.com
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: true
